version: "3.9"

services:
  server:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/mydb?schema=public
      JWT_PRIVATE_KEY: DLSgmlgnd@*$*&@SDGKLG
    ports:
      - "2800:2800"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - 1000:5432
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
